import { useState } from 'react';
import { Badge } from '../../components/ui';

interface Discharge { id: string; patientName: string; mrn: string; ward: string; doctor: string; diagnosis: string; plannedDate: string; status: 'In Planning' | 'Ready' | 'Discharged' | 'Delayed'; medications: string[]; followUp: string; transport: string; checklist: { item: string; done: boolean }[]; }

const DISCHARGES: Discharge[] = [
  { id: 'DC-001', patientName: 'Kwame Asante', mrn: 'MRN-2024-0891', ward: 'Medical Ward A', doctor: 'Dr. Sarah Johnson', diagnosis: 'Community-acquired pneumonia', plannedDate: '2026-08-24', status: 'Ready',
    medications: ['Amoxicillin 500mg TDS × 5 days', 'Paracetamol 500mg TDS PRN × 3 days'],
    followUp: 'OPD review in 2 weeks', transport: 'Private car',
    checklist: [{ item: 'Medications prescribed', done: true }, { item: 'Discharge summary written', done: true }, { item: 'Prescriptions printed', done: true }, { item: 'Follow-up appointment booked', done: true }, { item: 'Patient education completed', done: true }, { item: 'Insurance clearance', done: true }, { item: 'Transport arranged', done: false }] },
  { id: 'DC-002', patientName: 'Akua Mensah', mrn: 'MRN-2024-0923', ward: 'Maternity Ward', doctor: 'Dr. Ama Darko', diagnosis: 'Normal vaginal delivery', plannedDate: '2026-08-24', status: 'In Planning',
    medications: ['Iron supplement 200mg BD × 6 weeks', 'Folic acid 5mg OD × 6 weeks'],
    followUp: '6-week postnatal visit', transport: 'Hospital ambulance',
    checklist: [{ item: 'Baby vaccination schedule', done: true }, { item: 'Mother education (breastfeeding)', done: true }, { item: 'Discharge summary written', done: false }, { item: 'Prescriptions printed', done: false }, { item: 'Follow-up booked', done: true }] },
  { id: 'DC-003', patientName: 'Nana Osei', mrn: 'MRN-2024-0756', ward: 'Surgical Ward', doctor: 'Dr. James Mensah', diagnosis: 'Post-appendectomy recovery', plannedDate: '2026-08-25', status: 'In Planning',
    medications: ['Co-amoxiclav 625mg TDS × 5 days', 'Ibuprofen 400mg TDS × 7 days'],
    followUp: 'Surgical OPD in 1 week', transport: 'Taxi',
    checklist: [{ item: 'Wound care instructions', done: true }, { item: 'Activity restrictions explained', done: false }, { item: 'Medications prescribed', done: true }, { item: 'Discharge summary written', done: false }] },
];

const STATUS_COLORS: Record<string, string> = { 'In Planning': 'bg-yellow-100 text-yellow-800', Ready: 'bg-green-100 text-green-800', Discharged: 'bg-blue-100 text-blue-800', Delayed: 'bg-red-100 text-red-800' };

export default function DischargePlanningEnhanced() {
  const [records] = useState<Discharge[]>(DISCHARGES);
  const [selected, setSelected] = useState<Discharge | null>(DISCHARGES[0] ?? null);
  const [filter, setFilter] = useState('');

  const filtered = records.filter((r) => !filter || r.status === filter);

  function printDischargeSummary(d: Discharge) {
    const html = `<!DOCTYPE html><html><head><title>Discharge Summary - ${d.patientName}</title>
<style>body{font-family:Arial;padding:30px;max-width:700px;margin:0 auto;}.header{text-align:center;border-bottom:3px double #000;padding-bottom:10px;margin-bottom:15px;}.header h2{font-size:18px;margin:0;}.header p{font-size:11px;color:#666;margin:2px 0;}.section{margin:12px 0;}.section h3{font-size:12px;font-weight:bold;border-bottom:1px solid #ccc;padding-bottom:3px;margin-bottom:5px;}.section p,.section li{font-size:12px;line-height:1.6;}.med{background:#f0fdf4;padding:4px 8px;border-left:3px solid #22c55e;margin:3px 0;font-size:11px;}.checklist{font-size:11px;}.checklist div{padding:2px 0;}.footer{margin-top:30px;border-top:1px solid #ccc;padding-top:10px;font-size:10px;color:#999;}</style></head><body>
<div class="header"><h2>GIHM-HIS Hospital</h2><p>Ghana Integrated Health Management System</p><p>Discharge Summary</p></div>
<div class="section"><h3>Patient Information</h3><p><strong>Name:</strong> ${d.patientName}<br/><strong>MRN:</strong> ${d.mrn}<br/><strong>Ward:</strong> ${d.ward}<br/><strong>Discharging Doctor:</strong> ${d.doctor}<br/><strong>Date:</strong> ${d.plannedDate}</p></div>
<div class="section"><h3>Diagnosis</h3><p>${d.diagnosis}</p></div>
<div class="section"><h3>Discharge Medications</h3>${d.medications.map((m) => `<div class="med">• ${m}</div>`).join('')}</div>
<div class="section"><h3>Follow-up</h3><p>${d.followUp}</p></div>
<div class="section"><h3>Patient Education</h3><ul><li>Take medications as prescribed</li><li>Return to hospital if symptoms worsen</li><li>Rest and avoid strenuous activity for 1 week</li><li>Drink plenty of fluids</li></ul></div>
<div class="section"><h3>Transport</h3><p>${d.transport}</p></div>
<div class="footer"><p>Generated by GIHM-HIS (ShaComputeC) · ${new Date().toLocaleString()}</p></div></body></html>`;
    const w = window.open('', '_blank');
    if (w) { w.document.write(html); w.document.close(); w.print(); }
  }

  return (
    <div className="space-y-6">
      <div><h1 className="text-2xl font-bold">Discharge Planning</h1><p className="text-gray-500">Patient discharge checklist, summary generation, and follow-up scheduling</p></div>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {['In Planning', 'Ready', 'Discharged', 'Delayed'].map((s) => (
          <button key={s} onClick={() => setFilter(filter === s ? '' : s)} className={`p-3 rounded-lg border text-center transition ${filter === s ? 'ring-2 ring-green-500 border-green-300' : 'border-slate-200 hover:bg-slate-50'}`}>
            <div className="text-xl font-bold">{records.filter((r) => r.status === s).length}</div><div className="text-xs text-slate-500">{s}</div>
          </button>
        ))}
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="space-y-3">
          {filtered.map((d) => {
            const completed = d.checklist.filter((c) => c.done).length;
            const pct = Math.round((completed / d.checklist.length) * 100);
            return (
              <div key={d.id} onClick={() => setSelected(d)} className={`bg-white rounded-lg border p-4 cursor-pointer transition-all hover:shadow-md ${selected?.id === d.id ? 'ring-2 ring-green-500' : ''}`}>
                <div className="flex items-center justify-between mb-1"><span className="font-semibold text-sm">{d.patientName}</span><Badge className={STATUS_COLORS[d.status]}>{d.status}</Badge></div>
                <div className="text-xs text-slate-500">{d.diagnosis} · {d.ward}</div>
                <div className="mt-2 flex items-center gap-2"><div className="flex-1 bg-slate-100 rounded-full h-1.5"><div className={`h-1.5 rounded-full ${pct === 100 ? 'bg-green-500' : 'bg-yellow-500'}`} style={{ width: `${pct}%` }} /></div><span className="text-[10px] text-slate-400">{completed}/{d.checklist.length}</span></div>
              </div>
            );
          })}
        </div>
        {selected && (
          <div className="lg:col-span-2 bg-white rounded-lg border p-5 space-y-4 h-fit sticky top-4">
            <div className="flex items-center justify-between"><div><h3 className="text-lg font-bold">{selected.patientName}</h3><p className="text-sm text-gray-500">{selected.mrn} · {selected.ward} · {selected.doctor}</p></div><Badge className={STATUS_COLORS[selected.status]}>{selected.status}</Badge></div>
            <div className="bg-blue-50 border border-blue-200 rounded p-3 text-sm"><strong>Diagnosis:</strong> {selected.diagnosis}<br/><strong>Planned Date:</strong> {selected.plannedDate}<br/><strong>Follow-up:</strong> {selected.followUp}<br/><strong>Transport:</strong> {selected.transport}</div>
            <div><h4 className="text-sm font-semibold mb-2">Discharge Medications</h4>{selected.medications.map((m, i) => <div key={i} className="bg-green-50 border-l-3 border-green-500 px-3 py-1.5 text-sm rounded mb-1">💊 {m}</div>)}</div>
            <div><h4 className="text-sm font-semibold mb-2">Discharge Checklist</h4><div className="space-y-1">{selected.checklist.map((c, i) => <div key={i} className="flex items-center gap-2 text-sm"><span className={c.done ? 'text-green-600' : 'text-slate-400'}>{c.done ? '✅' : '⬜'}</span><span className={c.done ? 'line-through text-slate-400' : ''}>{c.item}</span></div>)}</div></div>
            <div className="flex gap-2"><button onClick={() => printDischargeSummary(selected)} className="bg-green-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-green-700">🖨️ Print Summary</button><button className="bg-blue-600 text-white px-4 py-2 rounded-lg text-sm font-medium">📋 Print Prescription</button><button className="border px-4 py-2 rounded-lg text-sm font-medium">📧 Send to OPD</button></div>
          </div>
        )}
      </div>
    </div>
  );
}
