#!/usr/bin/env bash
# =============================================================================
# GIHM-HIS facility edge installer (docs/16 §2, deploy/edge/README.md)
#
# Idempotent: safe to re-run. Existing .env is left untouched; images are
# rebuilt; the API health check gates the success message.
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info() { echo -e "${GREEN}[edge]${NC} $*"; }
warn() { echo -e "${YELLOW}[edge]${NC} $*"; }
die()  { echo -e "${RED}[edge]${NC} $*" >&2; exit 1; }

# --- prerequisites ----------------------------------------------------------
command -v docker >/dev/null 2>&1 || die "Docker Engine is required (https://docs.docker.com/engine/install/)."
docker compose version >/dev/null 2>&1 || die "The docker compose plugin is required (https://docs.docker.com/compose/install/)."

LAN_IP="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
WEB_PORT="${WEB_PORT:-8080}"

# --- configuration ----------------------------------------------------------
ENV_FILE=.env
if [ ! -f "$ENV_FILE" ]; then
  if command -v openssl >/dev/null 2>&1; then
    JWT_SECRET="$(openssl rand -hex 32)"
  else
    JWT_SECRET="$(head -c 64 /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 64)"
  fi
  cat > "$ENV_FILE" <<EOF
# GIHM-HIS facility edge configuration — generated by install.sh.
# Keep this file private: it contains the JWT signing secret.
JWT_SECRET=${JWT_SECRET}
WEB_ORIGIN=http://${LAN_IP:-localhost}:${WEB_PORT}

# --- Upstream national/regional platform relay (docs/16 §2, §5) -------------
# Uncomment and fill in to bubble the facility's offline mutation log up to
# the national platform through the shared /sync/mutations protocol:
# EDGE_RELAY_URL=https://national.example.gh
# EDGE_RELAY_USERNAME=edge-service@national.gh
# EDGE_RELAY_PASSWORD=change-me
# EDGE_RELAY_DEVICE_ID=edge-$(hostname 2>/dev/null || echo local)
# EDGE_RELAY_INTERVAL_MINUTES=1
EOF
  chmod 600 "$ENV_FILE"
  info "Created $ENV_FILE with a fresh JWT_SECRET."
else
  warn "$ENV_FILE already exists — leaving it untouched (edit it to change settings)."
fi

mkdir -p backups

# --- build + start ----------------------------------------------------------
info "Building images (first run takes a few minutes)…"
docker compose up -d --build

# --- health gate ------------------------------------------------------------
info "Waiting for the API to become healthy…"
for i in $(seq 1 60); do
  if docker compose exec -T api node -e "fetch('http://127.0.0.1:4000/api/v1/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))" >/dev/null 2>&1; then
    break
  fi
  [ "$i" = 60 ] && die "API did not become healthy within 120s — see 'docker compose logs api'."
  sleep 2
done

LAN_IP="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
info "Facility edge is up."
echo
echo "  Web (workstations):  http://${LAN_IP:-<this-host>}:${WEB_PORT}"
echo "  API (localhost):     http://127.0.0.1:${API_PORT:-4000}"
echo "  Swagger docs:        http://127.0.0.1:${API_PORT:-4000}/docs"
echo
info "Next steps:"
echo "  1. Open the web UI, sign in, and verify the facility's data."
echo "  2. Point every workstation at http://${LAN_IP:-<this-host>}:${WEB_PORT} (LAN only)."
echo "  3. Configure the upstream relay in $ENV_FILE (README §Upstream relay)."
echo "  4. Schedule nightly backups:  crontab -e"
echo "       0 2 * * * $(pwd)/backup.sh"
